### PR TITLE
remove old language module and add pt-br language

### PR DESCRIPTION
**Pull request by Swellington-Soares**
## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by mafewtm** [comment]
Fix all the spaces you removed

**Comment by mafewtm** [comment]
Youre missing a lot of the old locale calls.

**Comment by Swellington-Soares** [comment]
> Youre missing a lot of the old locale calls.

Strange, I checked here and it wasn't missing, I'm checking to see if I'm using an outdated version.

**Comment by Swellington-Soares** [comment]
> Youre missing a lot of the old locale calls.

fixed.

**Review by mafewtm — APPROVED** [review]

**Pull request merged**
